const { body } = require('express-validator');

const idField = (path) => body(path).isString().notEmpty().withMessage('Thiếu localId');

const orderValidators = [
  body('orders').optional().isArray({ max: 5000 }).withMessage('orders phải là mảng'),
  idField('orders.*.localId'),
  body('orders.*.orderCode').optional().isString(),
  body('orders.*.totalAmount').optional().isFloat({ min: 0 }),
  body('orders.*.subtotalAmount').optional().isFloat({ min: 0 }),
  body('orders.*.discount').optional().isFloat({ min: 0 }),
  body('orders.*.discountType').optional().isString(),
  body('orders.*.paymentMethod').optional().isString(),
  body('orders.*.cashierId').optional().isString(),
  body('orders.*.cashierName').optional().isString(),
  body('orders.*.customerLocalId').optional({ nullable: true }).isString(),
  body('orders.*.customerPhone').optional({ nullable: true }).isString(),
  body('orders.*.pointsUsed').optional().isFloat({ min: 0 }),
  body('orders.*.pointsEarned').optional().isFloat({ min: 0 }),
  body('orders.*.status').optional().isString(),
  body('orders.*.createdAt').optional().isInt({ min: 0 }),
  body('orders.*.note').optional().isString(),
  body('orderItems').optional().isArray({ max: 20000 }).withMessage('orderItems phải là mảng'),
  idField('orderItems.*.localId'),
  body('orderItems.*.orderLocalId').optional().isString(),
  body('orderItems.*.productLocalId').optional().isString(),
  body('orderItems.*.productName').optional().isString(),
  body('orderItems.*.price').optional().isFloat({ min: 0 }),
  body('orderItems.*.qty').optional().isFloat({ min: 0 }),
  body('orderItems.*.subtotal').optional().isFloat({ min: 0 }),
];

const masterValidators = [
  body('products').optional().isArray({ max: 10000 }).withMessage('products phải là mảng'),
  idField('products.*.localId'),
  body('products.*.productCode').optional().isString(),
  body('products.*.barcode').optional().isString(),
  body('products.*.name').optional().isString(),
  body('products.*.price').optional().isFloat({ min: 0 }),
  body('products.*.costPrice').optional().isFloat({ min: 0 }),
  body('products.*.stock').optional().isFloat(),
  body('products.*.unit').optional().isString(),
  body('products.*.categoryId').optional().isString(),
  body('products.*.allowPoints').optional().isBoolean(),
  body('products.*.deleted').optional().isBoolean(),
  body('products.*.createdAt').optional().isInt({ min: 0 }),
  body('products.*.updatedAt').optional().isInt({ min: 0 }),
  body('customers').optional().isArray({ max: 10000 }).withMessage('customers phải là mảng'),
  idField('customers.*.localId'),
  body('customers.*.customerCode').optional({ nullable: true }).isString(),
  body('customers.*.name').optional({ nullable: true }).isString(),
  body('customers.*.nickname').optional({ nullable: true }).isString(),
  body('customers.*.phone').optional({ nullable: true }).isString(),
  body('customers.*.address').optional({ nullable: true }).isString(),
  body('customers.*.area').optional({ nullable: true }).isString(),
  body('customers.*.ward').optional({ nullable: true }).isString(),
  body('customers.*.group').optional({ nullable: true }).isString(),
  body('customers.*.dateOfBirth').optional({ nullable: true }).isString(),
  body('customers.*.gender').optional({ nullable: true }).isString(),
  body('customers.*.email').optional({ nullable: true }).isString(),
  body('customers.*.facebook').optional({ nullable: true }).isString(),
  body('customers.*.note').optional({ nullable: true }).isString(),
  body('customers.*.points').optional().isFloat({ min: 0 }),
  body('customers.*.debt').optional().isFloat({ min: 0 }),
  body('customers.*.createdAt').optional().isInt({ min: 0 }),
  body('customers.*.updatedAt').optional().isInt({ min: 0 }),
];

const returnValidators = [
  body('returns').optional().isArray({ max: 5000 }).withMessage('returns phải là mảng'),
  idField('returns.*.localId'),
  body('returns.*.returnCode').optional().isString(),
  body('returns.*.orderLocalId').optional().isString(),
  body('returns.*.orderCode').optional().isString(),
  body('returns.*.exchangeOrderLocalId').optional().isString(),
  body('returns.*.exchangeOrderCode').optional().isString(),
  body('returns.*.cashierId').optional().isString(),
  body('returns.*.cashierName').optional().isString(),
  body('returns.*.customerLocalId').optional({ nullable: true }).isString(),
  body('returns.*.customerPhone').optional({ nullable: true }).isString(),
  body('returns.*.totalReturnAmount').optional().isFloat({ min: 0 }),
  body('returns.*.totalExchangeAmount').optional().isFloat({ min: 0 }),
  body('returns.*.netAmount').optional().isFloat(),
  body('returns.*.paymentMethod').optional().isString(),
  body('returns.*.amountPaid').optional().isFloat({ min: 0 }),
  body('returns.*.createdAt').optional().isInt({ min: 0 }),
  body('returns.*.exchangeItems').optional().isArray(),
  body('returnItems').optional().isArray({ max: 20000 }).withMessage('returnItems phải là mảng'),
  idField('returnItems.*.localId'),
  body('returnItems.*.returnLocalId').optional().isString(),
  body('returnItems.*.productLocalId').optional().isString(),
  body('returnItems.*.productName').optional().isString(),
  body('returnItems.*.price').optional().isFloat({ min: 0 }),
  body('returnItems.*.qty').optional().isFloat({ min: 0 }),
  body('returnItems.*.subtotal').optional().isFloat({ min: 0 }),
];

module.exports = {
  orderValidators,
  masterValidators,
  returnValidators,
};
